title: Brick Fiction
tagline: '&#35;klocki &#35;indiedev'
description: >-
  Blog i recenzje klocków LEGO i nie tylko. Do tego luźne wpisy i proces tworzenia gier.
url: 'https://brickfiction.pl/'
baseurl: ''
lang: pl
timezone: Europe/Warsaw
nullitics_url: 'https://brickfiction.pl/'
avatar: /assets/img/avatar.jpg
style_version: 5

twitter:
  username: brick_fiction

social:
  name: brickfiction.pl
  email: kontakt@brickfiction.pl
  links: []

google_analytics:
  id:
  pv:
    proxy_endpoint:
    cache_path:

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      permalink: /posts/:title/
  - scope:
      path: ''
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json
  - yarn.lock
  - Dockerfile
  - docker-compose.yml
  - .playwright-cli

jekyll-archives:
  enabled: [categories]
  layouts:
    category: archive
  permalinks:
    category: /categories/:name/

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
